name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: corepack enable
    - run: corepack prepare
    - run: pnpm install
    - run: pnpm prettier --ignore-path=.prettierignore --config=.prettierrc.json --write .
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'style: format code with prettier'
        title: 'style: format code with prettier'
        branch: format-code
        base: ${{ github.head_ref || github.ref_name }}
        delete-branch: true
  test:
    needs: format
    name: Build & Test
    strategy:
      matrix:
        os:
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: corepack enable
    - run: corepack prepare
    - run: |
        node --version
        pnpm --version
    - run: pnpm install
    - run: |
        pnpm playwright install
        pnpm playwright install-deps
    - run: pnpm playwright test
    - if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.os }}
        path: playwright-report/
        retention-days: 30
