name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
permissions:
  actions: write
  contents: write
  workflows: write
jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
      with:
        node-version: lts/*
    - run: corepack enable
    - run: corepack prepare
    - run: |
        node --version
        pnpm --version
    - run: pnpm install
    - run: |
        pnpm playwright install
        pnpm playwright install-deps
    - run: pnpm playwright test
    - if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      with:
        name: playwright-report-${{ matrix.os }}
        path: playwright-report/
        retention-days: 30
  format:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
      with:
        node-version: lts/*
    - run: corepack enable
    - run: corepack prepare
    - run: pnpm install
    - run: pnpm prettier --ignore-path=.prettierignore --config=.prettierrc.json --write .
    - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
      with:
        message: 'style: format code with prettier'
        add: .
