name: Build & Test
"on":
 push:
   branches:
     - "*"
 pull_request:
   branches:
     - "*"
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: irby/setup-node-nvm@master
       with:
         node-version: lts/*
     - run: |
         node --version
         npm --version
     - run: npm ci
     - run: |
         npx playwright install
         npx playwright install-deps
     - run: npx playwright test
     - if: always()
       uses: actions/upload-artifact@v4
       with:
         name: playwright-report
         path: playwright-report/
         retention-days: 30