name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: lts/*
      - run: corepack enable
      - run: corepack prepare
      - run: pnpm install
      - run: pnpm prettier --ignore-path=.prettierignore --config=.prettierrc.json --write .
      - uses: test-room-7/action-update-file@be6fb6d9c59d5ec4b56542f2e8ad2516a99e3402 # v2
        with:
          file-path: |
            .github/workflows/ci.yml
            pnpm-lock.yaml
          commit-msg: "style: format code with prettier"
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
